# Generated by Django 3.2 on 2021-06-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
